
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.Array;
import java.util.Arrays;
import java.util.Queue;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hamza
 */
public class SiteApplication extends javax.swing.JFrame {

    /**
     * Creates new form SiteApplication
     */
    public SiteApplication() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        googleOpen = new javax.swing.JButton();
        twitterOpen = new javax.swing.JButton();
        faceboolOpen = new javax.swing.JButton();
        tiktokOpen = new javax.swing.JButton();
        website_area = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ch1_button = new javax.swing.JButton();
        ch1_save_radio = new javax.swing.JRadioButton();
        ch2_button = new javax.swing.JButton();
        ch2_save_radio = new javax.swing.JRadioButton();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SITEAPP");
        setBounds(new java.awt.Rectangle(600, 300, 0, 0));

        googleOpen.setText("GOOGLE");
        googleOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                googleOpenActionPerformed(evt);
            }
        });

        twitterOpen.setText("TWITTER");
        twitterOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twitterOpenActionPerformed(evt);
            }
        });

        faceboolOpen.setText("FACEBOOK");
        faceboolOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faceboolOpenActionPerformed(evt);
            }
        });

        tiktokOpen.setText("TIKTOK");
        tiktokOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiktokOpenActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Enter Site Name");

        ch1_button.setText("Channel 1");
        ch1_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch1_buttonActionPerformed(evt);
            }
        });

        ch1_save_radio.setText("Save");

        ch2_button.setText("Channel 2");
        ch2_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch2_buttonActionPerformed(evt);
            }
        });

        ch2_save_radio.setText("Save");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(website_area, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(googleOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(faceboolOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(twitterOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(tiktokOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ch1_button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ch1_save_radio)
                                .addGap(80, 80, 80)
                                .addComponent(ch2_button, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ch2_save_radio)))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tiktokOpen, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(googleOpen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(faceboolOpen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(twitterOpen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(website_area, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ch1_button, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(ch1_save_radio)
                    .addComponent(ch2_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ch2_save_radio))
                .addContainerGap(158, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void googleOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_googleOpenActionPerformed
        try {
            ChannelOperations ch = new ChannelOperations("google");
            ch.openChannel("google");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(SiteApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_googleOpenActionPerformed

    private void faceboolOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faceboolOpenActionPerformed
        try {
            ChannelOperations ch = new ChannelOperations("facebook");
            ch.openChannel("facebook");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(SiteApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
           
    }//GEN-LAST:event_faceboolOpenActionPerformed

    private void twitterOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twitterOpenActionPerformed
        
        try {
            ChannelOperations ch = new ChannelOperations("twitter");
            ch.openChannel("twitter");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(SiteApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_twitterOpenActionPerformed

    private void tiktokOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiktokOpenActionPerformed
        
        try {
            ChannelOperations ch = new ChannelOperations("tiktok");
            ch.openChannel("tiktok");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(SiteApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
          
    }//GEN-LAST:event_tiktokOpenActionPerformed

    @SuppressWarnings("empty-statement")
    private void ch1_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch1_buttonActionPerformed
        String web = website_area.getText();
        ChannelOperations ch = new ChannelOperations("ch1",web);
        if(ch1_save_radio.isSelected()){
                
                    if(ch.isControl()==false){
                        JOptionPane.showMessageDialog(SiteApplication.this,"Already Registered");                        
                        
                    }
                    else{
                        try {
                            ch.saveChannel("ch1", web);
                    
                    
                        } catch (FileNotFoundException ex) {
                            Logger.getLogger(SiteApplication.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
        }
        else{
            if(ch.isControl()==true){
                try {
                     ChannelOperations chh = new ChannelOperations("ch1");
                    String openWeb = chh.getWeb();
                    chh.openChannel2(openWeb);
              
              
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(SiteApplication.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
            else{
                JOptionPane.showMessageDialog(SiteApplication.this,"Please save channel");
            }
            
        }
 
    }//GEN-LAST:event_ch1_buttonActionPerformed

    private void ch2_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch2_buttonActionPerformed
      String web = website_area.getText();
        ChannelOperations ch = new ChannelOperations("ch2",web);
        if(ch2_save_radio.isSelected()){
                
                    if(ch.isControl()==false){
                        JOptionPane.showMessageDialog(SiteApplication.this,"Already Registered");                        
                        
                    }
                    else{
                        try {
                            ch.saveChannel("ch2", web);
                    
                    
                        } catch (FileNotFoundException ex) {
                            Logger.getLogger(SiteApplication.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
        }
        else{
            if(ch.isControl()==true){
                try {
                     ChannelOperations chh = new ChannelOperations("ch2");
                    String openWeb = chh.getWeb();
                    chh.openChannel2(openWeb);
              
              
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(SiteApplication.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
            else{
                try{
                JOptionPane.showMessageDialog(SiteApplication.this,"Please save channel");
                }
                catch(NullPointerException n){
                   
                }
            }
            
        }
 
        
    }//GEN-LAST:event_ch2_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SiteApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SiteApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SiteApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SiteApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SiteApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton ch1_button;
    private javax.swing.JRadioButton ch1_save_radio;
    private javax.swing.JButton ch2_button;
    private javax.swing.JRadioButton ch2_save_radio;
    private javax.swing.JButton faceboolOpen;
    private javax.swing.JButton googleOpen;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton tiktokOpen;
    private javax.swing.JButton twitterOpen;
    private javax.swing.JTextField website_area;
    // End of variables declaration//GEN-END:variables

    private void Thread(int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
